# Portainer

version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer${MY_HOSTNAME}
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${GELF_ADDRESS}"
        tag: "container_name={{.Name}}"
