version: '3'

networks:
  graynet:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    networks:
      - graynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.40.0.207:12201"
        tag: "container_name={{.Name}}"
